-- seed.sql — Datos iniciales
begin;
insert into public.categorias_cita (slug,nombre,emoji,color,descripcion,orden) values ('romantico','Romántico','💕','#F2B8A0','Planes para enamorarse',1) on conflict (slug) do nothing;
insert into public.categorias_cita (slug,nombre,emoji,color,descripcion,orden) values ('airelibre','Aire libre','🌿','#8FB39A','Naturaleza y ciudad',2) on conflict (slug) do nothing;
insert into public.categorias_cita (slug,nombre,emoji,color,descripcion,orden) values ('cultural','Cultural','🎭','#7FB5B5','Arte, museos y teatro',3) on conflict (slug) do nothing;
insert into public.categorias_cita (slug,nombre,emoji,color,descripcion,orden) values ('comida','Comida rica','🍽️','#D9A05B','Sabores para compartir',4) on conflict (slug) do nothing;
insert into public.categorias_cita (slug,nombre,emoji,color,descripcion,orden) values ('rumba','Rumba','💃','#C9896B','Noche y alegría',5) on conflict (slug) do nothing;
insert into public.categorias_cita (slug,nombre,emoji,color,descripcion,orden) values ('casero','Plan casero','🛋️','#A8D5BA','Calienticos en casa',6) on conflict (slug) do nothing;
insert into public.categorias_cita (slug,nombre,emoji,color,descripcion,orden) values ('escapada','Escapada','🚗','#7A9E7E','Pueblitos cerca de Bogotá',7) on conflict (slug) do nothing;
insert into public.actividades (nombre,descripcion,emoji,precio,dias_permitidos,nota,es_comodin) values ('Subir en teleférico y ver el atardecer','Vista increíble de la ciudad al caer el sol','🚡',2,null,null,false) on conflict do nothing;
insert into public.actividades (nombre,descripcion,emoji,precio,dias_permitidos,nota,es_comodin) values ('Subir a pie por el sendero','Caminata con esfuerzo y recompensa visual','🥾',1,null,'Temprano; verificar horario',false) on conflict do nothing;
insert into public.actividades (nombre,descripcion,emoji,precio,dias_permitidos,nota,es_comodin) values ('Comer con vista a la ciudad','Almuerzo o comida con panorama de Bogotá','🍽️',3,null,null,false) on conflict do nothing;
insert into public.actividades (nombre,descripcion,emoji,precio,dias_permitidos,nota,es_comodin) values ('Ver las luces de la ciudad','La noche bogotana desde las alturas','🌃',1,null,null,false) on conflict do nothing;
insert into public.actividades (nombre,descripcion,emoji,precio,dias_permitidos,nota,es_comodin) values ('Cena con vista','Cena romántica mirando las luces','🕯️',4,null,null,false) on conflict do nothing;
insert into public.actividades (nombre,descripcion,emoji,precio,dias_permitidos,nota,es_comodin) values ('Mercado de pulgas','Tesoros, antigüedades y buen ambiente','🧺',1,'{0}','Domingos y festivos',false) on conflict do nothing;
insert into public.actividades (nombre,descripcion,emoji,precio,dias_permitidos,nota,es_comodin) values ('Cena en el centro histórico','Restaurante con historia en Usaquén','🍝',3,null,null,false) on conflict do nothing;
insert into public.actividades (nombre,descripcion,emoji,precio,dias_permitidos,nota,es_comodin) values ('Café y postre','Una pausa dulce de media tarde','🍰',2,null,null,false) on conflict do nothing;
insert into public.actividades (nombre,descripcion,emoji,precio,dias_permitidos,nota,es_comodin) values ('Tour de grafitis','Arte callejero en La Candelaria','🎨',1,null,'Verificar horarios del tour',false) on conflict do nothing;
insert into public.actividades (nombre,descripcion,emoji,precio,dias_permitidos,nota,es_comodin) values ('Museo del Oro o Museo Botero','Clásicos bogotanos para una mañana cultural','🏛️',2,null,'Verificar días de apertura',false) on conflict do nothing;
insert into public.actividades (nombre,descripcion,emoji,precio,dias_permitidos,nota,es_comodin) values ('Chocolate santafereño con queso','Tradición caliente del centro','☕',1,null,null,false) on conflict do nothing;
insert into public.actividades (nombre,descripcion,emoji,precio,dias_permitidos,nota,es_comodin) values ('Cena en un restaurante especial','Una fecha para recordar','🍷',4,null,null,false) on conflict do nothing;
insert into public.actividades (nombre,descripcion,emoji,precio,dias_permitidos,nota,es_comodin) values ('Brunch','Desayuno-almuerzo sin afán','🥐',3,null,null,false) on conflict do nothing;
insert into public.actividades (nombre,descripcion,emoji,precio,dias_permitidos,nota,es_comodin) values ('Ruta de cafés de especialidad','El mejor café de la ciudad, taza a taza','☕',2,null,null,false) on conflict do nothing;
insert into public.actividades (nombre,descripcion,emoji,precio,dias_permitidos,nota,es_comodin) values ('Mercado de flores','Color y olor a Bogotá a primera hora','🌸',1,null,'Muy temprano en la mañana',false) on conflict do nothing;
insert into public.actividades (nombre,descripcion,emoji,precio,dias_permitidos,nota,es_comodin) values ('Probar frutas exóticas','Pitahaya, lulo, uchuva y más','🍓',1,null,null,false) on conflict do nothing;
insert into public.actividades (nombre,descripcion,emoji,precio,dias_permitidos,nota,es_comodin) values ('Desayuno típico','Caldo de costilla y arepa con queso','🍲',2,null,null,false) on conflict do nothing;
insert into public.actividades (nombre,descripcion,emoji,precio,dias_permitidos,nota,es_comodin) values ('Caminar por los jardines y el tropicario','Un respiro verde en la ciudad','🌿',2,null,null,false) on conflict do nothing;
insert into public.actividades (nombre,descripcion,emoji,precio,dias_permitidos,nota,es_comodin) values ('Picnic','Manta, snacks y risas al aire libre','🧺',1,null,null,false) on conflict do nothing;
insert into public.actividades (nombre,descripcion,emoji,precio,dias_permitidos,nota,es_comodin) values ('Caminar alrededor del lago','Paseo tranquilo con vista al agua','🚶',1,null,null,false) on conflict do nothing;
insert into public.actividades (nombre,descripcion,emoji,precio,dias_permitidos,nota,es_comodin) values ('Visitar la Biblioteca Virgilio Barco','Un edificio hermoso para perderse','📚',1,null,null,false) on conflict do nothing;
insert into public.actividades (nombre,descripcion,emoji,precio,dias_permitidos,nota,es_comodin) values ('Montar bici juntos','La ciclovía más famosa del mundo','🚴',1,'{0}','Domingos y festivos en la mañana',false) on conflict do nothing;
insert into public.actividades (nombre,descripcion,emoji,precio,dias_permitidos,nota,es_comodin) values ('Caminata por el cerro','Naturaleza y trocha en La Vieja','🥾',1,null,'Requiere registro previo; verificar días y horario',false) on conflict do nothing;
insert into public.actividades (nombre,descripcion,emoji,precio,dias_permitidos,nota,es_comodin) values ('Función bajo el domo','Planetario en pantalla gigante','🔭',2,null,null,false) on conflict do nothing;
insert into public.actividades (nombre,descripcion,emoji,precio,dias_permitidos,nota,es_comodin) values ('Obra, concierto u ópera','Noche elegante en el Colón o el Mayor','🎭',3,null,null,false) on conflict do nothing;
insert into public.actividades (nombre,descripcion,emoji,precio,dias_permitidos,nota,es_comodin) values ('Película de cine independiente','Cine con alma en la Cinemateca','🎬',2,null,null,false) on conflict do nothing;
insert into public.actividades (nombre,descripcion,emoji,precio,dias_permitidos,nota,es_comodin) values ('Cenar y bailar hasta tarde','El clásico de la sabana','🪩',4,null,null,false) on conflict do nothing;
insert into public.actividades (nombre,descripcion,emoji,precio,dias_permitidos,nota,es_comodin) values ('Bailar salsa','Pista y sabor en la Zona T','💃',3,null,null,false) on conflict do nothing;
insert into public.actividades (nombre,descripcion,emoji,precio,dias_permitidos,nota,es_comodin) values ('Karaoke','Cantar a pulmón abierto','🎤',3,null,null,false) on conflict do nothing;
insert into public.actividades (nombre,descripcion,emoji,precio,dias_permitidos,nota,es_comodin) values ('Cócteles','Brindis y buena conversación','🍸',3,null,null,false) on conflict do nothing;
insert into public.actividades (nombre,descripcion,emoji,precio,dias_permitidos,nota,es_comodin) values ('Jugar tejo con cerveza y mechas','El deporte nacional, versión íntima','🎯',2,null,null,false) on conflict do nothing;
insert into public.actividades (nombre,descripcion,emoji,precio,dias_permitidos,nota,es_comodin) values ('Catedral de Sal','Maravilla subterránea de Zipaquirá','⛪',2,null,null,false) on conflict do nothing;
insert into public.actividades (nombre,descripcion,emoji,precio,dias_permitidos,nota,es_comodin) values ('Almorzar en el pueblo','Plato típico en la plaza de Zipaquirá','🍲',2,null,null,false) on conflict do nothing;
insert into public.actividades (nombre,descripcion,emoji,precio,dias_permitidos,nota,es_comodin) values ('Caminata a la laguna sagrada','Camino empedrado hacia el agua','🏞️',2,null,'Verificar horario',false) on conflict do nothing;
insert into public.actividades (nombre,descripcion,emoji,precio,dias_permitidos,nota,es_comodin) values ('Recorrer el pueblo','Calles empedradas y artesanías','🏘️',1,null,null,false) on conflict do nothing;
insert into public.actividades (nombre,descripcion,emoji,precio,dias_permitidos,nota,es_comodin) values ('Escalada en roca con guía','Aventura con seguridad en Suesca','🧗',3,null,null,false) on conflict do nothing;
insert into public.actividades (nombre,descripcion,emoji,precio,dias_permitidos,nota,es_comodin) values ('Caminata por las rocas','Paisaje de otro mundo','🪨',1,null,null,false) on conflict do nothing;
insert into public.actividades (nombre,descripcion,emoji,precio,dias_permitidos,nota,es_comodin) values ('Caminata a la cascada La Chorrera','La cascada más alta de Cundinamarca','💦',2,null,null,false) on conflict do nothing;
insert into public.actividades (nombre,descripcion,emoji,precio,dias_permitidos,nota,es_comodin) values ('Termales','Aguas calientes para relajarse','♨️',2,null,null,false) on conflict do nothing;
insert into public.actividades (nombre,descripcion,emoji,precio,dias_permitidos,nota,es_comodin) values ('Cocinar juntos','Receta nueva y postre obligatorio','🍳',1,null,null,false) on conflict do nothing;
insert into public.actividades (nombre,descripcion,emoji,precio,dias_permitidos,nota,es_comodin) values ('Noche de pelis con crispetas','Maratón con manta y chocolate','🍿',1,null,null,false) on conflict do nothing;
insert into public.actividades (nombre,descripcion,emoji,precio,dias_permitidos,nota,es_comodin) values ('Juegos de mesa','Competencia sana y risas','🎲',1,null,null,false) on conflict do nothing;
insert into public.actividades (nombre,descripcion,emoji,precio,dias_permitidos,nota,es_comodin) values ('Spa en casa','Mascarillas, velas y calma','🧖',1,null,null,false) on conflict do nothing;
insert into public.actividades (nombre,descripcion,emoji,precio,dias_permitidos,nota,es_comodin) values ('Karaoke en casa','El concierto más cucho y bonito','🎤',1,null,null,false) on conflict do nothing;
insert into public.actividades (nombre,descripcion,emoji,precio,dias_permitidos,nota,es_comodin) values ('Sesión de fotos juntos','Selfies o cámara, pero juntos','📸',1,null,null,true) on conflict do nothing;
insert into public.actividades (nombre,descripcion,emoji,precio,dias_permitidos,nota,es_comodin) values ('Café y charla larga','Sin afán, solo nosotros','☕',1,null,null,true) on conflict do nothing;
insert into public.actividades (nombre,descripcion,emoji,precio,dias_permitidos,nota,es_comodin) values ('Caminar sin rumbo','La ciudad se descubre a pie','🚶',1,null,null,true) on conflict do nothing;
insert into public.actividades (nombre,descripcion,emoji,precio,dias_permitidos,nota,es_comodin) values ('Probar algo que nunca hayamos comido','Aventura comestible','🌮',2,null,null,true) on conflict do nothing;
insert into public.lugares (nombre,zona,categorias,descripcion,emoji,precio,duracion,link_maps,es_escapada) values ('Monserrate','Cerros orientales','{romantico,airelibre}','El cerro más famoso de Bogotá','⛰️',2,'Medio día','https://www.google.com/maps/search/?api=1&query=Monserrate%20Bogot%C3%A1',false) on conflict do nothing;
insert into public.lugar_actividad (lugar_id, actividad_id) select l.id, a.id from public.lugares l, public.actividades a where l.nombre = 'Monserrate' and a.nombre = 'Subir en teleférico y ver el atardecer' on conflict do nothing;
insert into public.lugar_actividad (lugar_id, actividad_id) select l.id, a.id from public.lugares l, public.actividades a where l.nombre = 'Monserrate' and a.nombre = 'Subir a pie por el sendero' on conflict do nothing;
insert into public.lugar_actividad (lugar_id, actividad_id) select l.id, a.id from public.lugares l, public.actividades a where l.nombre = 'Monserrate' and a.nombre = 'Comer con vista a la ciudad' on conflict do nothing;
insert into public.lugares (nombre,zona,categorias,descripcion,emoji,precio,duracion,link_maps,es_escapada) values ('Miradores de La Calera','Vía a La Calera (≈30 min)','{romantico,comida}','Vistas espectaculares sobre la ciudad','🌄',3,'Noche','https://www.google.com/maps/search/?api=1&query=Miradores%20de%20La%20Calera%20La%20Calera',false) on conflict do nothing;
insert into public.lugar_actividad (lugar_id, actividad_id) select l.id, a.id from public.lugares l, public.actividades a where l.nombre = 'Miradores de La Calera' and a.nombre = 'Ver las luces de la ciudad' on conflict do nothing;
insert into public.lugar_actividad (lugar_id, actividad_id) select l.id, a.id from public.lugares l, public.actividades a where l.nombre = 'Miradores de La Calera' and a.nombre = 'Cena con vista' on conflict do nothing;
insert into public.lugares (nombre,zona,categorias,descripcion,emoji,precio,duracion,link_maps,es_escapada) values ('Usaquén','Norte','{romantico,comida,cultural}','Barrio colonial con mucho encanto','🏘️',2,'Medio día','https://www.google.com/maps/search/?api=1&query=Usaqu%C3%A9n%20Bogot%C3%A1',false) on conflict do nothing;
insert into public.lugar_actividad (lugar_id, actividad_id) select l.id, a.id from public.lugares l, public.actividades a where l.nombre = 'Usaquén' and a.nombre = 'Mercado de pulgas' on conflict do nothing;
insert into public.lugar_actividad (lugar_id, actividad_id) select l.id, a.id from public.lugares l, public.actividades a where l.nombre = 'Usaquén' and a.nombre = 'Cena en el centro histórico' on conflict do nothing;
insert into public.lugar_actividad (lugar_id, actividad_id) select l.id, a.id from public.lugares l, public.actividades a where l.nombre = 'Usaquén' and a.nombre = 'Café y postre' on conflict do nothing;
insert into public.lugares (nombre,zona,categorias,descripcion,emoji,precio,duracion,link_maps,es_escapada) values ('La Candelaria y el Centro','Centro histórico','{cultural}','Colonias, iglesias y arte','🏛️',1,'Medio día','https://www.google.com/maps/search/?api=1&query=La%20Candelaria%20y%20el%20Centro%20Bogot%C3%A1',false) on conflict do nothing;
insert into public.lugar_actividad (lugar_id, actividad_id) select l.id, a.id from public.lugares l, public.actividades a where l.nombre = 'La Candelaria y el Centro' and a.nombre = 'Tour de grafitis' on conflict do nothing;
insert into public.lugar_actividad (lugar_id, actividad_id) select l.id, a.id from public.lugares l, public.actividades a where l.nombre = 'La Candelaria y el Centro' and a.nombre = 'Museo del Oro o Museo Botero' on conflict do nothing;
insert into public.lugar_actividad (lugar_id, actividad_id) select l.id, a.id from public.lugares l, public.actividades a where l.nombre = 'La Candelaria y el Centro' and a.nombre = 'Chocolate santafereño con queso' on conflict do nothing;
insert into public.lugares (nombre,zona,categorias,descripcion,emoji,precio,duracion,link_maps,es_escapada) values ('Zona G, Quinta Camacho y Chapinero Alto','Chapinero','{comida,romantico}','Restaurantes y cafés de otro nivel','🍴',4,'Noche','https://www.google.com/maps/search/?api=1&query=Zona%20G%2C%20Quinta%20Camacho%20y%20Chapinero%20Alto%20Bogot%C3%A1',false) on conflict do nothing;
insert into public.lugar_actividad (lugar_id, actividad_id) select l.id, a.id from public.lugares l, public.actividades a where l.nombre = 'Zona G, Quinta Camacho y Chapinero Alto' and a.nombre = 'Cena en un restaurante especial' on conflict do nothing;
insert into public.lugar_actividad (lugar_id, actividad_id) select l.id, a.id from public.lugares l, public.actividades a where l.nombre = 'Zona G, Quinta Camacho y Chapinero Alto' and a.nombre = 'Brunch' on conflict do nothing;
insert into public.lugar_actividad (lugar_id, actividad_id) select l.id, a.id from public.lugares l, public.actividades a where l.nombre = 'Zona G, Quinta Camacho y Chapinero Alto' and a.nombre = 'Ruta de cafés de especialidad' on conflict do nothing;
insert into public.lugares (nombre,zona,categorias,descripcion,emoji,precio,duracion,link_maps,es_escapada) values ('Plaza de mercado de Paloquemao','Centro','{comida,cultural}','El mercado más sabroso de la ciudad','🛒',1,'Mañana','https://www.google.com/maps/search/?api=1&query=Plaza%20de%20mercado%20de%20Paloquemao%20Bogot%C3%A1',false) on conflict do nothing;
insert into public.lugar_actividad (lugar_id, actividad_id) select l.id, a.id from public.lugares l, public.actividades a where l.nombre = 'Plaza de mercado de Paloquemao' and a.nombre = 'Mercado de flores' on conflict do nothing;
insert into public.lugar_actividad (lugar_id, actividad_id) select l.id, a.id from public.lugares l, public.actividades a where l.nombre = 'Plaza de mercado de Paloquemao' and a.nombre = 'Probar frutas exóticas' on conflict do nothing;
insert into public.lugar_actividad (lugar_id, actividad_id) select l.id, a.id from public.lugares l, public.actividades a where l.nombre = 'Plaza de mercado de Paloquemao' and a.nombre = 'Desayuno típico' on conflict do nothing;
insert into public.lugares (nombre,zona,categorias,descripcion,emoji,precio,duracion,link_maps,es_escapada) values ('Jardín Botánico de Bogotá','Occidente (Calle 63 con Av. 68)','{airelibre,romantico}','Más de 20 hectáreas de naturaleza','🌺',2,'Medio día','https://www.google.com/maps/search/?api=1&query=Jard%C3%ADn%20Bot%C3%A1nico%20de%20Bogot%C3%A1%20Bogot%C3%A1',false) on conflict do nothing;
insert into public.lugar_actividad (lugar_id, actividad_id) select l.id, a.id from public.lugares l, public.actividades a where l.nombre = 'Jardín Botánico de Bogotá' and a.nombre = 'Caminar por los jardines y el tropicario' on conflict do nothing;
insert into public.lugares (nombre,zona,categorias,descripcion,emoji,precio,duracion,link_maps,es_escapada) values ('Parque Simón Bolívar','Teusaquillo','{airelibre}','El pulmón verde de Bogotá','🌳',1,'Medio día','https://www.google.com/maps/search/?api=1&query=Parque%20Sim%C3%B3n%20Bol%C3%ADvar%20Bogot%C3%A1',false) on conflict do nothing;
insert into public.lugar_actividad (lugar_id, actividad_id) select l.id, a.id from public.lugares l, public.actividades a where l.nombre = 'Parque Simón Bolívar' and a.nombre = 'Picnic' on conflict do nothing;
insert into public.lugar_actividad (lugar_id, actividad_id) select l.id, a.id from public.lugares l, public.actividades a where l.nombre = 'Parque Simón Bolívar' and a.nombre = 'Caminar alrededor del lago' on conflict do nothing;
insert into public.lugar_actividad (lugar_id, actividad_id) select l.id, a.id from public.lugares l, public.actividades a where l.nombre = 'Parque Simón Bolívar' and a.nombre = 'Visitar la Biblioteca Virgilio Barco' on conflict do nothing;
insert into public.lugares (nombre,zona,categorias,descripcion,emoji,precio,duracion,link_maps,es_escapada) values ('Ciclovía','Varias vías','{airelibre}','Bogotá se llena de bici y risas','🚴',1,'Mañana','https://www.google.com/maps/search/?api=1&query=Ciclov%C3%ADa%20Bogot%C3%A1',false) on conflict do nothing;
insert into public.lugar_actividad (lugar_id, actividad_id) select l.id, a.id from public.lugares l, public.actividades a where l.nombre = 'Ciclovía' and a.nombre = 'Montar bici juntos' on conflict do nothing;
insert into public.lugares (nombre,zona,categorias,descripcion,emoji,precio,duracion,link_maps,es_escapada) values ('Quebrada La Vieja','Cerros orientales (Chapinero)','{airelibre}','Senderismo cerca a casa','🥾',1,'Mañana','https://www.google.com/maps/search/?api=1&query=Quebrada%20La%20Vieja%20Bogot%C3%A1',false) on conflict do nothing;
insert into public.lugar_actividad (lugar_id, actividad_id) select l.id, a.id from public.lugares l, public.actividades a where l.nombre = 'Quebrada La Vieja' and a.nombre = 'Caminata por el cerro' on conflict do nothing;
insert into public.lugares (nombre,zona,categorias,descripcion,emoji,precio,duracion,link_maps,es_escapada) values ('Planetario de Bogotá','Centro','{cultural,romantico}','El universo en pantalla gigante','🔭',2,'Un par de horas','https://www.google.com/maps/search/?api=1&query=Planetario%20de%20Bogot%C3%A1%20Bogot%C3%A1',false) on conflict do nothing;
insert into public.lugar_actividad (lugar_id, actividad_id) select l.id, a.id from public.lugares l, public.actividades a where l.nombre = 'Planetario de Bogotá' and a.nombre = 'Función bajo el domo' on conflict do nothing;
insert into public.lugares (nombre,zona,categorias,descripcion,emoji,precio,duracion,link_maps,es_escapada) values ('Teatro Colón o Teatro Mayor','Centro o Suba','{cultural,romantico}','Noches de gala y buen arte','🎭',3,'Noche','https://www.google.com/maps/search/?api=1&query=Teatro%20Col%C3%B3n%20o%20Teatro%20Mayor%20Bogot%C3%A1',false) on conflict do nothing;
insert into public.lugar_actividad (lugar_id, actividad_id) select l.id, a.id from public.lugares l, public.actividades a where l.nombre = 'Teatro Colón o Teatro Mayor' and a.nombre = 'Obra, concierto u ópera' on conflict do nothing;
insert into public.lugares (nombre,zona,categorias,descripcion,emoji,precio,duracion,link_maps,es_escapada) values ('Cinemateca de Bogotá','Centro','{cultural}','Cine de culto y conversación','🎬',2,'Un par de horas','https://www.google.com/maps/search/?api=1&query=Cinemateca%20de%20Bogot%C3%A1%20Bogot%C3%A1',false) on conflict do nothing;
insert into public.lugar_actividad (lugar_id, actividad_id) select l.id, a.id from public.lugares l, public.actividades a where l.nombre = 'Cinemateca de Bogotá' and a.nombre = 'Película de cine independiente' on conflict do nothing;
insert into public.lugares (nombre,zona,categorias,descripcion,emoji,precio,duracion,link_maps,es_escapada) values ('Andrés Carne de Res','Chía (≈45 min)','{rumba,comida}','El plan de rumba por excelencia','🥩',4,'Noche larga','https://www.google.com/maps/search/?api=1&query=Andr%C3%A9s%20Carne%20de%20Res%20Ch%C3%ADa',false) on conflict do nothing;
insert into public.lugar_actividad (lugar_id, actividad_id) select l.id, a.id from public.lugares l, public.actividades a where l.nombre = 'Andrés Carne de Res' and a.nombre = 'Cenar y bailar hasta tarde' on conflict do nothing;
insert into public.lugares (nombre,zona,categorias,descripcion,emoji,precio,duracion,link_maps,es_escapada) values ('Zona T y Zona Rosa','Norte','{rumba}','Bares y buena energía','🎉',3,'Noche','https://www.google.com/maps/search/?api=1&query=Zona%20T%20y%20Zona%20Rosa%20Bogot%C3%A1',false) on conflict do nothing;
insert into public.lugar_actividad (lugar_id, actividad_id) select l.id, a.id from public.lugares l, public.actividades a where l.nombre = 'Zona T y Zona Rosa' and a.nombre = 'Bailar salsa' on conflict do nothing;
insert into public.lugar_actividad (lugar_id, actividad_id) select l.id, a.id from public.lugares l, public.actividades a where l.nombre = 'Zona T y Zona Rosa' and a.nombre = 'Karaoke' on conflict do nothing;
insert into public.lugar_actividad (lugar_id, actividad_id) select l.id, a.id from public.lugares l, public.actividades a where l.nombre = 'Zona T y Zona Rosa' and a.nombre = 'Cócteles' on conflict do nothing;
insert into public.lugares (nombre,zona,categorias,descripcion,emoji,precio,duracion,link_maps,es_escapada) values ('Cancha de tejo','Varias zonas','{rumba}','Tradición y puntería','🎯',2,'Un par de horas','https://www.google.com/maps/search/?api=1&query=Cancha%20de%20tejo%20Bogot%C3%A1',false) on conflict do nothing;
insert into public.lugar_actividad (lugar_id, actividad_id) select l.id, a.id from public.lugares l, public.actividades a where l.nombre = 'Cancha de tejo' and a.nombre = 'Jugar tejo con cerveza y mechas' on conflict do nothing;
insert into public.lugares (nombre,zona,categorias,descripcion,emoji,precio,duracion,link_maps,es_escapada) values ('Zipaquirá','A ≈1 h de Bogotá','{escapada,cultural}','La ciudad blanca','⛪',3,'Día completo','https://www.google.com/maps/search/?api=1&query=Zipaquir%C3%A1%20Zipaquir%C3%A1',true) on conflict do nothing;
insert into public.lugar_actividad (lugar_id, actividad_id) select l.id, a.id from public.lugares l, public.actividades a where l.nombre = 'Zipaquirá' and a.nombre = 'Catedral de Sal' on conflict do nothing;
insert into public.lugar_actividad (lugar_id, actividad_id) select l.id, a.id from public.lugares l, public.actividades a where l.nombre = 'Zipaquirá' and a.nombre = 'Almorzar en el pueblo' on conflict do nothing;
insert into public.lugares (nombre,zona,categorias,descripcion,emoji,precio,duracion,link_maps,es_escapada) values ('Guatavita','A ≈1 h 30 de Bogotá','{escapada,airelibre}','Laguna sagrada y pueblo colonial','🏞️',3,'Día completo','https://www.google.com/maps/search/?api=1&query=Guatavita%20Guatavita',true) on conflict do nothing;
insert into public.lugar_actividad (lugar_id, actividad_id) select l.id, a.id from public.lugares l, public.actividades a where l.nombre = 'Guatavita' and a.nombre = 'Caminata a la laguna sagrada' on conflict do nothing;
insert into public.lugar_actividad (lugar_id, actividad_id) select l.id, a.id from public.lugares l, public.actividades a where l.nombre = 'Guatavita' and a.nombre = 'Recorrer el pueblo' on conflict do nothing;
insert into public.lugares (nombre,zona,categorias,descripcion,emoji,precio,duracion,link_maps,es_escapada) values ('Suesca','A ≈1 h 30 de Bogotá','{escapada,airelibre}','Rocas y aventura','🧗',3,'Día completo','https://www.google.com/maps/search/?api=1&query=Suesca%20Suesca',true) on conflict do nothing;
insert into public.lugar_actividad (lugar_id, actividad_id) select l.id, a.id from public.lugares l, public.actividades a where l.nombre = 'Suesca' and a.nombre = 'Escalada en roca con guía' on conflict do nothing;
insert into public.lugar_actividad (lugar_id, actividad_id) select l.id, a.id from public.lugares l, public.actividades a where l.nombre = 'Suesca' and a.nombre = 'Caminata por las rocas' on conflict do nothing;
insert into public.lugares (nombre,zona,categorias,descripcion,emoji,precio,duracion,link_maps,es_escapada) values ('Choachí','A ≈1 h de Bogotá','{escapada,airelibre}','Cascada y termales','💦',3,'Día completo','https://www.google.com/maps/search/?api=1&query=Choach%C3%AD%20Choach%C3%AD',true) on conflict do nothing;
insert into public.lugar_actividad (lugar_id, actividad_id) select l.id, a.id from public.lugares l, public.actividades a where l.nombre = 'Choachí' and a.nombre = 'Caminata a la cascada La Chorrera' on conflict do nothing;
insert into public.lugar_actividad (lugar_id, actividad_id) select l.id, a.id from public.lugares l, public.actividades a where l.nombre = 'Choachí' and a.nombre = 'Termales' on conflict do nothing;
insert into public.lugares (nombre,zona,categorias,descripcion,emoji,precio,duracion,link_maps,es_escapada) values ('En casa','Casa','{casero}','El mejor plan: nosotros dos','🏠',1,'Noche','https://www.google.com/maps/search/?api=1&query=En%20casa%20Bogot%C3%A1',false) on conflict do nothing;
insert into public.lugar_actividad (lugar_id, actividad_id) select l.id, a.id from public.lugares l, public.actividades a where l.nombre = 'En casa' and a.nombre = 'Cocinar juntos' on conflict do nothing;
insert into public.lugar_actividad (lugar_id, actividad_id) select l.id, a.id from public.lugares l, public.actividades a where l.nombre = 'En casa' and a.nombre = 'Noche de pelis con crispetas' on conflict do nothing;
insert into public.lugar_actividad (lugar_id, actividad_id) select l.id, a.id from public.lugares l, public.actividades a where l.nombre = 'En casa' and a.nombre = 'Juegos de mesa' on conflict do nothing;
insert into public.lugar_actividad (lugar_id, actividad_id) select l.id, a.id from public.lugares l, public.actividades a where l.nombre = 'En casa' and a.nombre = 'Spa en casa' on conflict do nothing;
insert into public.lugar_actividad (lugar_id, actividad_id) select l.id, a.id from public.lugares l, public.actividades a where l.nombre = 'En casa' and a.nombre = 'Karaoke en casa' on conflict do nothing;
insert into public.lugares (nombre,zona,descripcion,emoji,precio,duracion,link_maps,es_sorpresa) values ('Sorpréndeme','Donde sea','Yo escojo el lugar perfecto para los dos','🎁',2,'Por definir',null,true) on conflict do nothing;
insert into public.actividades (nombre,descripcion,emoji,es_sorpresa) values ('Sorpréndeme','Yo arreglo la actividad','🎁',true) on conflict do nothing;
insert into public.franjas (nombre,emoji,horario,orden) values ('Mañana','☀️','8 a. m. a 12 m.',1) on conflict do nothing;
insert into public.franjas (nombre,emoji,horario,orden) values ('Tarde','🌤️','12 m. a 5 p. m.',2) on conflict do nothing;
insert into public.franjas (nombre,emoji,horario,orden) values ('Atardecer','🌇','5 a 7 p. m.',3) on conflict do nothing;
insert into public.franjas (nombre,emoji,horario,orden) values ('Noche','🌙','Desde las 7 p. m.',4) on conflict do nothing;
insert into public.franjas (nombre,emoji,horario,orden) values ('Día completo','🗓️','Todo el día',5) on conflict do nothing;
insert into public.opciones_llevar (tipo,nombre,descripcion,emoji) values ('detalle','Flores','Mi clásico para ti','💐') on conflict do nothing;
insert into public.opciones_llevar (tipo,nombre,descripcion,emoji) values ('detalle','Chocolates','Dulce para una persona dulce','🍫') on conflict do nothing;
insert into public.opciones_llevar (tipo,nombre,descripcion,emoji) values ('detalle','Una carta escrita a mano','Para leer despacio','💌') on conflict do nothing;
insert into public.opciones_llevar (tipo,nombre,descripcion,emoji) values ('detalle','Mi postre favorito','El que siempre pido','🍰') on conflict do nothing;
insert into public.opciones_llevar (tipo,nombre,descripcion,emoji) values ('detalle','Una playlist hecha para mí','Nuestra lista de canciones','🎧') on conflict do nothing;
insert into public.opciones_llevar (tipo,nombre,descripcion,emoji) values ('detalle','Vino para brindar','Por nosotros','🍷') on conflict do nothing;
insert into public.opciones_llevar (tipo,nombre,descripcion,emoji) values ('detalle','Una chaqueta extra por si hace frío','Porque en Bogotá el clima cambia','🧥') on conflict do nothing;
insert into public.opciones_llevar (tipo,nombre,descripcion,emoji) values ('detalle','Paraguas, porque es Bogotá','Por si llueve','☔') on conflict do nothing;
insert into public.opciones_llevar (tipo,nombre,descripcion,emoji) values ('detalle','Cámara instantánea','Para guardar el momento','📷') on conflict do nothing;
insert into public.opciones_llevar (tipo,nombre,descripcion,emoji) values ('detalle','Manta para picnic','Por si nos provoca sentarnos','🧺') on conflict do nothing;
insert into public.opciones_llevar (tipo,nombre,descripcion,emoji) values ('detalle','Nada, solo tú','Eso es suficiente','😌') on conflict do nothing;
insert into public.opciones_llevar (tipo,nombre,descripcion,emoji,es_sorpresa) values ('detalle','Sorpréndeme','Yo te llevo una sorpresita','🎁',true) on conflict do nothing;
insert into public.opciones_llevar (tipo,nombre,descripcion,emoji) values ('vestimenta','Casual y cómodos','Sudadera y tenis','👟') on conflict do nothing;
insert into public.opciones_llevar (tipo,nombre,descripcion,emoji) values ('vestimenta','Elegantes','Nos emperifollamos','✨') on conflict do nothing;
insert into public.opciones_llevar (tipo,nombre,descripcion,emoji) values ('vestimenta','Deportivos','Listos para moverse','🏃') on conflict do nothing;
insert into public.opciones_llevar (tipo,nombre,descripcion,emoji) values ('vestimenta','Combinados del mismo color','Parejita coordinada','👫') on conflict do nothing;
insert into public.opciones_llevar (tipo,nombre,descripcion,emoji) values ('vestimenta','Abrigados, con ruana y bufanda','Para el frío bogotano','🧣') on conflict do nothing;
insert into public.categorias_preguntas (slug,nombre,emoji,color,orden) values ('conocernos','Para conocernos más','🔍','#8FB39A',1) on conflict (slug) do nothing;
insert into public.categorias_preguntas (slug,nombre,emoji,color,orden) values ('recuerdos','Nuestros recuerdos','📸','#F2B8A0',2) on conflict (slug) do nothing;
insert into public.categorias_preguntas (slug,nombre,emoji,color,orden) values ('suenos','Sueños y futuro','🌱','#7FB5B5',3) on conflict (slug) do nothing;
insert into public.categorias_preguntas (slug,nombre,emoji,color,orden) values ('divertidas','Divertidas e hipotéticas','🎲','#A3B18A',4) on conflict (slug) do nothing;
insert into public.categorias_preguntas (slug,nombre,emoji,color,orden) values ('profundas','Profundas','🌊','#7A9E7E',5) on conflict (slug) do nothing;
insert into public.categorias_preguntas (slug,nombre,emoji,color,orden) values ('coquetas','Coquetas','😏','#D9A05B',6) on conflict (slug) do nothing;
insert into public.preguntas (categoria_slug, texto) values ('conocernos', '¿Qué canción te devuelve a tu infancia en dos segundos?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('conocernos', '¿Cuál es un pequeño placer que te arregla el día?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('conocernos', '¿Qué es algo que sabes hacer y casi nadie sabe?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('conocernos', '¿Cuál fue tu materia favorita en el colegio y por qué?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('conocernos', '¿Qué olor te transporta a tu niñez?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('conocernos', '¿Qué serie te podrías ver mil veces sin cansarte?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('conocernos', '¿Qué es lo que más te gusta de vivir en Colombia?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('conocernos', '¿Cuál es tu comida favorita de diciembre?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('conocernos', '¿Qué te hace reír sin falta?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('conocernos', '¿Cuál era tu sueño cuando eras niño o niña?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('conocernos', '¿Qué habilidad te gustaría tener que no tienes?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('conocernos', '¿Qué es lo primero que notas en una persona?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('conocernos', '¿Qué libro o película te marcó la vida?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('conocernos', '¿Cuál es tu lugar favorito de Bogotá?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('conocernos', '¿Qué te emociona aprender últimamente?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('conocernos', '¿Cuál es tu recuerdo más feliz de este año?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('conocernos', '¿Qué tipo de música te acompaña cuando estás triste?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('conocernos', '¿Qué es algo que siempre quisiste probar y no has hecho?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('conocernos', '¿Cómo te describirías con tres palabras?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('conocernos', '¿Qué es lo que más valoras de una amistad?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('recuerdos', '¿Qué fue lo primero que pensaste de mí?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('recuerdos', '¿Qué momento nuestro volverías a vivir tal cual?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('recuerdos', '¿Cuál fue la cita que más te gustó hasta ahora?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('recuerdos', '¿Qué te hizo saber que yo era diferente?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('recuerdos', '¿Cuál es el apodo que más te gusta que te diga?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('recuerdos', '¿Qué detalle mío te enamoró?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('recuerdos', '¿Cuál fue la primera vez que me viste de verdad?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('recuerdos', '¿Qué viaje o salida juntos recuerdas con más cariño?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('recuerdos', '¿Cuál fue el primer regalo que me diste?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('recuerdos', '¿Qué canción te recuerda a nosotros?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('recuerdos', '¿Cuál es la foto nuestra que más te gusta?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('recuerdos', '¿Qué fue lo más chistoso que nos ha pasado?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('recuerdos', '¿Cuándo supiste que querías que esto fuera en serio?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('recuerdos', '¿Qué consejo te di que todavía aplicas?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('recuerdos', '¿Cuál fue el mejor día que hemos tenido?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('recuerdos', '¿Qué es algo que hacíamos al principio y extrañas?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('recuerdos', '¿Qué te dije que no se te ha olvidado?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('recuerdos', '¿Cuál fue la comida más rica que hemos compartido?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('recuerdos', '¿Qué lugar de Bogotá te recuerda a mí?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('recuerdos', '¿Cuál ha sido nuestro mayor logro como pareja?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('suenos', 'Si pudiéramos vivir un año en otro país, ¿cuál escogerías?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('suenos', '¿Cómo sería un domingo perfecto dentro de diez años?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('suenos', '¿Qué meta quieres cumplir este año?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('suenos', 'Si tuviéramos una casa de campo, ¿cómo sería?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('suenos', '¿Qué te gustaría que hiciéramos juntos el próximo año?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('suenos', '¿Cómo te imaginas nuestra vida en cinco años?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('suenos', '¿Qué aventura te gustaría vivir conmigo primero?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('suenos', 'Si pudiéramos tener una mascota juntos, ¿cuál sería?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('suenos', '¿Qué tradición te gustaría crear conmigo?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('suenos', '¿Qué es algo que quieres aprender antes de los 40?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('suenos', '¿Dónde te gustaría ver el atardecer conmigo?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('suenos', 'Si abriéramos un negocio, ¿de qué sería?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('suenos', '¿Qué viaje sueñas hacer conmigo algún día?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('suenos', '¿Cómo te gustaría celebrar nuestro primer aniversario?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('suenos', '¿Qué es lo que más te ilusiona del futuro?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('suenos', 'Si pudiéramos cambiar una cosa del mundo, ¿cuál sería?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('suenos', '¿Qué tipo de familia te gustaría formar?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('suenos', '¿Qué es algo que quieres perdonarte?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('suenos', '¿Qué te gustaría lograr con nuestra relación?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('suenos', '¿Cómo sería tu retiro ideal conmigo?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('divertidas', 'Si fueras un plato colombiano, ¿cuál serías y por qué?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('divertidas', 'Si fuéramos un dúo de superhéroes, ¿qué poder tendría cada uno?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('divertidas', 'Si tuvieras que comer lo mismo una semana, ¿qué sería?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('divertidas', '¿Qué personaje de película te representaría mejor?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('divertidas', 'Si pudiéramos cambiarnos de cuerpo un día, ¿qué haríamos?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('divertidas', '¿Qué superpoder inútil te encantaría tener?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('divertidas', 'Si nuestra relación fuera una canción, ¿cuál sería?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('divertidas', '¿Qué animal serías si no fueras humano?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('divertidas', 'Si pudieras volver atrás y decirle algo a tu yo de 10 años, ¿qué sería?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('divertidas', '¿Qué harías si ganaras la lotería mañana?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('divertidas', 'Si tuviera que elegir entre café y chocolate, ¿cuál ganarías?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('divertidas', '¿Qué superpoder tendría yo en nuestra historia?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('divertidas', 'Si nuestro amor fuera un destino de viaje, ¿cuál sería?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('divertidas', '¿Qué harías si pudieras hablar con los animales un día?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('divertidas', 'Si fuéramos famosos, ¿por qué seriamos?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('divertidas', '¿Qué harías si no tuvieras que trabajar un mes?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('divertidas', 'Si pudieras cenar con alguien, vivo o no, ¿con quién sería?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('divertidas', '¿Qué superpoder tendría nuestra mascota ideal?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('divertidas', 'Si te tocara vivir en una película, ¿cuál sería?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('divertidas', '¿Qué harías si pudieras teletransportarte por un día?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('profundas', '¿Qué es algo que te cuesta pedir, aunque lo necesites?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('profundas', '¿Qué te enseñó la etapa más difícil de tu vida?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('profundas', '¿Qué es algo de lo que te arrepientes?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('profundas', '¿Qué significa para ti estar enamorado?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('profundas', '¿Qué te da miedo del futuro?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('profundas', '¿Qué es lo que más valoras en una persona?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('profundas', '¿Qué es algo que todavía no me has contado?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('profundas', '¿Qué te hace sentir seguro o segura?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('profundas', '¿Qué es algo que te gustaría cambiar de ti?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('profundas', '¿Qué aprendiste de tu familia?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('profundas', '¿Qué es algo que necesitas escuchar más seguido?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('profundas', '¿Cuál ha sido tu mayor lección de amor?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('profundas', '¿Qué te hace sentir acompañado o acompañada?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('profundas', '¿Qué es algo que te gustaría perdonar?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('profundas', '¿Qué es lo que más te cuesta aceptar?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('profundas', '¿Qué te hace sentir vivo o viva?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('profundas', '¿Qué es algo que te gustaría lograr antes de morir?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('profundas', '¿Qué te enseñó tu última relación?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('profundas', '¿Qué es algo que te hace sentir orgulloso o orgullosa de ti?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('profundas', '¿Qué es lo que más te cuesta soltar?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('coquetas', '¿Qué es lo que más te gusta que haga sin que me lo pidas?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('coquetas', '¿En qué momento supiste que te gustaba?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('coquetas', '¿Qué es lo que más te atrae de mí?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('coquetas', '¿Qué gesto mío te pone de buenas instantáneamente?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('coquetas', '¿Cuál es tu parte favorita de mí?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('coquetas', '¿Qué es lo que más te gusta de cómo te miro?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('coquetas', '¿Qué es lo que más te gusta de nuestros besos?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('coquetas', '¿Qué es lo que más te gusta de cómo te trato?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('coquetas', '¿Qué es lo que más te gusta de nuestra conexión?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('coquetas', '¿Qué es lo que más te gusta de estar conmigo?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('coquetas', '¿Qué es lo que más te gusta de cómo te escucho?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('coquetas', '¿Qué es lo que más te gusta de cómo te abrazo?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('coquetas', '¿Qué es lo que más te gusta de nuestras risas?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('coquetas', '¿Qué es lo que más te gusta de cómo te cuido?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('coquetas', '¿Qué es lo que más te gusta de cómo te hago sentir?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('coquetas', '¿Qué es lo que más te gusta de cómo te sorprendo?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('coquetas', '¿Qué es lo que más te gusta de cómo te apoyo?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('coquetas', '¿Qué es lo que más te gusta de cómo te elijo?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('coquetas', '¿Qué es lo que más te gusta de cómo te quiero?') on conflict do nothing;
insert into public.preguntas (categoria_slug, texto) values ('coquetas', '¿Qué es lo que más te gusta de nosotros?') on conflict do nothing;
commit;